### ISSUE TITLE
Add options to search a movie by year

### ISSUE THREAD

**Issue by fernahh** [fernahh/imdbtr#10]
The [Movie API](http://www.theimdbapi.org/) provides some params to find a movie. We can provide options to user, like:

```
imdbtr "Deadpool" -y 2013
```

**TODO**

- [x] Search by year

**Comment by ndedic** [comment]
I'll have a look at this

**Comment by martini97** [comment]
Would it be useful to add filtering by genre? If so I'd like to implement it, thanks :)

**Comment by fernahh** [comment]
@martini97 did you have a look at [API provider](http://www.theimdbapi.org/)? there is not a easy way to develop this feature. 🤔

**Comment by martini97** [comment]
I took a look at the API, and I think the best way to do it would be processing the API response (using a filter)

**Comment by fernahh** [comment]
@martini97 can you create a issue to describe this feature? or just send a pull request with the idea :)

**Comment by martini97** [comment]
@fernahh I will send you a PR later today
