### ISSUE TITLE
Similar implementation for Slack

### ISSUE THREAD

**Issue by vishaltelangre** [fernahh/imdbtr#3]
Nice work! 

Other day [I did similar thing for Slack](https://github.com/vishaltelangre/cowboy).

See following gif:

![](https://camo.githubusercontent.com/d1b2c014766cd893d1bea574e1bd87409a900a54/68747470733a2f2f7261772e6769746875622e636f6d2f76697368616c74656c616e6772652f636f77626f792f6d61737465722f7374617469632f736e65616b5f7065616b2e6769663f763d6175673134)

**Comment by fernahh** [comment]
Nice! :)
