### ISSUE TITLE
API Key required

### ISSUE THREAD

**Issue by theuves** [fernahh/imdbtr#9]
Now, the API requires a key to access the data.

See &lt;http://www.omdbapi.com/#usage&gt;.

***

On GitHub I found some valid keys, like `2f6435d9`, `df751404`, and `1ca32dee`.

**Comment by fernahh** [comment]
Hi, @theuves!

I have solved this issue at [v1.0.0](https://github.com/fernahh/imdbtr/releases/tag/v1.0.0).
